name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multipleline script
        run: |
          node -v
          npm -v
      #   /usr/bin/cat /etc/resolv.conf
      - name: python command 
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-command2: 
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: create a directory
        run: get-location 
      - name: directory bash
        run: pwd
        shell: bash

